### ISSUE TITLE
Canvas2D recursive error for getImageData

### ISSUE THREAD

**Issue by andreaordonselli** [GastonZalba/ol-street-view#5]
Good morning,
I've been getting this recursive error in the browser console for about a week:
![image](https://user-images.githubusercontent.com/89784373/196136946-3ff26d9c-7689-442f-b930-e889f3cfd806.png)

I investigated to understand what was causing the error and realized that it is ol-street-view. The error is reproducible in your online examples as well when you move the streetview pointer in the map.

![image](https://user-images.githubusercontent.com/89784373/196139494-ea1baea2-7934-412f-a6d7-4e5c13b2ff2b.png)

In my project the error is connected to an important slowness of the web map, which is generated above all when using the measurement and drawing tool ![image](https://user-images.githubusercontent.com/89784373/196136987-82af2818-67a4-4a35-9076-4fee788c0e25.png) ![image](https://user-images.githubusercontent.com/89784373/196137017-c9698871-9423-49e6-a4e2-334f7ddf0f0a.png)

I've uploaded an entire project to this location if you want to take a look at it.
https://www.ordonselli.com/canvas2d_error/ente/demo/

If I disable the call to ol-street-view in the index.html or delete the code in the .js everything goes back to working quickly.
Can you help me solve the problem?
Thank you.

openlayers 6.15.1
ol-street-view 2.0.1

**Comment by GastonZalba** [comment]
Hi, I'll take a look at it as soon as I can.

**Comment by GastonZalba** [comment]
Hi, i made some improvements... I found that the original panorama event `pov_changed` was firing multiple times when no pov was changed (only the position), and the `position_changed` was firing twice... in both cases i do not why. They are fixed in version 2.0.2 but most of the warnings will still persist. I looked at some of the openlayers [examples](https://openlayers.org/en/latest/examples/select-features.html) and the same warnings are displayed when there are vectors in the extent and a select event is triggered... so, i guess it's normal to some degree (?).

Let me know if it got better... but l'll take another look in the future.

**Comment by andreaordonselli** [comment]
Your fixed has completely solved the problem when using the measure and drawing function.
A thousand thanks.

Some warnings remained when using the map with the streetview pointer while traveling but the speed of the system is not affected.
Thank you again.

**Comment by GastonZalba** [comment]
Great!
